AWSTemplateFormatVersion: '2010-09-09'
Outputs:
  InputTopicARN:
    Description: 'SNS Topic ARN, destination for CWP Alerts'
    Value:
      Ref: InputTopic
  PagerDutyLambdaFunction: 
    Description: 'Name of the Lambda Function created'
    Value: 
      Ref: CwpPagerDutyFunction
Parameters:
  PagerDutyIntegrationKey:
    Default: ''
    Description: 'REQUIRED - PagerDuty integration (routing) key'
    Type: String
  PagerDutySeverity:
    Default: 'critical'
    Description: 'REQUIRED - PagerDuty event severity level for alerts (values: critical/error/warning/info)'
    Type: String
  CwpScoreFilter:
    Default: '7,8,9,10'
    Description: 'REQUIRED - CWP risk scores which will trigger a PagerDuty alert (comma separated values: 1 through 10)'
    Type: String
Resources:
  InputTopic:
    Type: AWS::SNS::Topic
  InputTopicPolicy:
    Properties:
      PolicyDocument:
        Id: CwpSnsPolicy
        Statement:
        - Action: sns:Publish
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::342443945406:root
          Resource:
            Ref: InputTopic
          Sid: CwpSnsPolicy
        Version: '2012-10-17'
      Topics:
      - Ref: InputTopic
    Type: AWS::SNS::TopicPolicy
  CwpPagerDutyFunction:
    Properties:
      CodeUri: 
        Bucket: 
          Fn::Join:
          - ''
          - - 'radware-cwp-devops-'
            - !Ref 'AWS::Region'
          # If deploying CFT manually, replace this join with a string (e.g. "Bucket: my-custom-bucket-name"
        Key: 'radware_cwp_pagerduty_integration/radware_cwp_pagerduty_integration.zip'
        # Key is the name of the zip file which contains lambda_function.py
      Description: 'CWP-Alerts -> SNS -> Lambda -> PagerDuty Events API'
      Environment:
        Variables:
          pd_integration_key:
            Ref: PagerDutyIntegrationKey
          pd_event_severity:
            Ref: PagerDutySeverity
          cwp_score_filter: 
            Ref: CwpScoreFilter
      Events:
        CwpAlerts:
          Type: SNS
          Properties:
            Topic: !Ref InputTopic
      FunctionName: !Ref AWS::StackName
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      Timeout: 7
    Type: AWS::Serverless::Function
  LambdaLogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CwpPagerDutyFunction}"
      RetentionInDays: 30
Transform: AWS::Serverless-2016-10-31
